//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lain.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string _0 {
            get {
                return ResourceManager.GetString("0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 128 KB.
        /// </summary>
        internal static string _128KB {
            get {
                return ResourceManager.GetString("128KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16 KB.
        /// </summary>
        internal static string _16KB {
            get {
                return ResourceManager.GetString("16KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 MB.
        /// </summary>
        internal static string _1MB {
            get {
                return ResourceManager.GetString("1MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 256 KB.
        /// </summary>
        internal static string _256KB {
            get {
                return ResourceManager.GetString("256KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 MB.
        /// </summary>
        internal static string _2MB {
            get {
                return ResourceManager.GetString("2MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32 KB.
        /// </summary>
        internal static string _32KB {
            get {
                return ResourceManager.GetString("32KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 512 KB.
        /// </summary>
        internal static string _512KB {
            get {
                return ResourceManager.GetString("512KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64 KB.
        /// </summary>
        internal static string _64KB {
            get {
                return ResourceManager.GetString("64KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./log.txt.
        /// </summary>
        internal static string _logtxt {
            get {
                return ResourceManager.GetString("/logtxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{m.Torrent.Name}] {m.Progress:0.00}% DL: {m.Monitor.DownloadRate / 1024:0.0}kB/s UL: {m.Monitor.UploadRate / 1024:0.0}kB/s.
        /// </summary>
        internal static string _mTorrentName_mProgress000_DLmMonitorDownloadRate_102400kB_sULmMonitorUploadRate_102400kB_s {
            get {
                return ResourceManager.GetString("[mTorrentName]mProgress000%DLmMonitorDownloadRate/102400kB/sULmMonitorUploadRate/" +
                        "102400kB/s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Torrents: .
        /// </summary>
        internal static string ActiveTorrents {
            get {
                return ResourceManager.GetString("ActiveTorrents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Torrents: {TorrentOperations.Managers!.Count}.
        /// </summary>
        internal static string ActiveTorrentsTorrentOperationsManagers_Count {
            get {
                return ResourceManager.GetString("ActiveTorrentsTorrentOperationsManagers!Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASCII color:.
        /// </summary>
        internal static string ASCIIcolor {
            get {
                return ResourceManager.GetString("ASCIIcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color:.
        /// </summary>
        internal static string Backgroundcolor {
            get {
                return ResourceManager.GetString("Backgroundcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        internal static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrightBlue.
        /// </summary>
        internal static string BrightBlue {
            get {
                return ResourceManager.GetString("BrightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrightCyan.
        /// </summary>
        internal static string BrightCyan {
            get {
                return ResourceManager.GetString("BrightCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrightGreen.
        /// </summary>
        internal static string BrightGreen {
            get {
                return ResourceManager.GetString("BrightGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrightMagenta.
        /// </summary>
        internal static string BrightMagenta {
            get {
                return ResourceManager.GetString("BrightMagenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrightRed.
        /// </summary>
        internal static string BrightRed {
            get {
                return ResourceManager.GetString("BrightRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrightYellow.
        /// </summary>
        internal static string BrightYellow {
            get {
                return ResourceManager.GetString("BrightYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        internal static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {c} .
        /// </summary>
        internal static string c {
            get {
                return ResourceManager.GetString("c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cfg.json.
        /// </summary>
        internal static string cfgjson {
            get {
                return ResourceManager.GetString("cfgjson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Color.
        /// </summary>
        internal static string ChooseColor {
            get {
                return ResourceManager.GetString("ChooseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        internal static string Cyan {
            get {
                return ResourceManager.GetString("Cyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkGray.
        /// </summary>
        internal static string DarkGray {
            get {
                return ResourceManager.GetString("DarkGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Download Path:.
        /// </summary>
        internal static string DefaultDownloadPath {
            get {
                return ResourceManager.GetString("DefaultDownloadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete: .
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted files at: {manager.SavePath}.
        /// </summary>
        internal static string DeletedfilesatmanagerSavePath {
            get {
                return ResourceManager.GetString("DeletedfilesatmanagerSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete downloaded files?.
        /// </summary>
        internal static string Deletedownloadedfiles_ {
            get {
                return ResourceManager.GetString("Deletedownloadedfiles?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted torrent: {manager.Torrent?.Name}.
        /// </summary>
        internal static string DeletedtorrentmanagerTorrent_Name {
            get {
                return ResourceManager.GetString("DeletedtorrentmanagerTorrent?Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete: {Settings.Current.Controls.RemoveTorrent}.
        /// </summary>
        internal static string DeleteSettingsCurrentControlsRemoveTorrent {
            get {
                return ResourceManager.GetString("DeleteSettingsCurrentControlsRemoveTorrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DHT: {Engine.Dht.State}.
        /// </summary>
        internal static string DHTEngineDhtState {
            get {
                return ResourceManager.GetString("DHTEngineDhtState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DHT port:.
        /// </summary>
        internal static string DHTport {
            get {
                return ResourceManager.GetString("DHTport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable ASCII.
        /// </summary>
        internal static string DisableASCII {
            get {
                return ResourceManager.GetString("DisableASCII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable colored hotkey information.
        /// </summary>
        internal static string Disablecoloredhotkeyinformation {
            get {
                return ResourceManager.GetString("Disablecoloredhotkeyinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading from magnet link....
        /// </summary>
        internal static string Downloadingfrommagnetlink {
            get {
                return ResourceManager.GetString("Downloadingfrommagnetlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download path:.
        /// </summary>
        internal static string Downloadpath {
            get {
                return ResourceManager.GetString("Downloadpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download path cannot be empty..
        /// </summary>
        internal static string Downloadpathcannotbeempty {
            get {
                return ResourceManager.GetString("Downloadpathcannotbeempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download path does not exist. Create it?.
        /// </summary>
        internal static string DownloadpathdoesnotexistCreateit_ {
            get {
                return ResourceManager.GetString("DownloadpathdoesnotexistCreateit?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download rate.
        /// </summary>
        internal static string Downloadrate {
            get {
                return ResourceManager.GetString("Downloadrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable detailed logging.
        /// </summary>
        internal static string Enabledetailedlogging {
            get {
                return ResourceManager.GetString("Enabledetailedlogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable DHT.
        /// </summary>
        internal static string EnableDHT {
            get {
                return ResourceManager.GetString("EnableDHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Port Forwarding.
        /// </summary>
        internal static string EnablePortForwarding {
            get {
                return ResourceManager.GetString("EnablePortForwarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting torrent: {ex.Message}.
        /// </summary>
        internal static string ErrordeletingtorrentexMessage {
            get {
                return ResourceManager.GetString("ErrordeletingtorrentexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading settings: {ex.Message}.
        /// </summary>
        internal static string ErrorloadingsettingsexMessage {
            get {
                return ResourceManager.GetString("ErrorloadingsettingsexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error pausing torrent: {ex.Message}.
        /// </summary>
        internal static string ErrorpausingtorrentexMessage {
            get {
                return ResourceManager.GetString("ErrorpausingtorrentexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error resuming torrent: {ex.Message}.
        /// </summary>
        internal static string ErrorresumingtorrentexMessage {
            get {
                return ResourceManager.GetString("ErrorresumingtorrentexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving fastresume data: {ex}.
        /// </summary>
        internal static string Errorsavingfastresumedataex {
            get {
                return ResourceManager.GetString("Errorsavingfastresumedataex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving settings: {ex.Message}.
        /// </summary>
        internal static string ErrorsavingsettingsexMessage {
            get {
                return ResourceManager.GetString("ErrorsavingsettingsexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving torrents: {ex.Message}.
        /// </summary>
        internal static string ErrorsavingtorrentsexMessage {
            get {
                return ResourceManager.GetString("ErrorsavingtorrentsexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting seeding: {ex.Message}.
        /// </summary>
        internal static string ErrorstartingseedingexMessage {
            get {
                return ResourceManager.GetString("ErrorstartingseedingexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error stopping seeding: {ex.Message}.
        /// </summary>
        internal static string ErrorstoppingseedingexMessage {
            get {
                return ResourceManager.GetString("ErrorstoppingseedingexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit?.
        /// </summary>
        internal static string Exit_ {
            get {
                return ResourceManager.GetString("Exit?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ex.Message}.
        /// </summary>
        internal static string exMessage {
            get {
                return ResourceManager.GetString("exMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast resume data saved for torrent: {Managers[index].Torrent?.Name}.
        /// </summary>
        internal static string FastresumedatasavedfortorrentManagers_index_Torrent_Name {
            get {
                return ResourceManager.GetString("FastresumedatasavedfortorrentManagers[index]Torrent?Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error.
        /// </summary>
        internal static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File/Folder:.
        /// </summary>
        internal static string File_Folder {
            get {
                return ResourceManager.GetString("File/Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus background color:.
        /// </summary>
        internal static string Focusbackgroundcolor {
            get {
                return ResourceManager.GetString("Focusbackgroundcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus text color:.
        /// </summary>
        internal static string Focustextcolor {
            get {
                return ResourceManager.GetString("Focustextcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate magnet link: {Settings.Current.Controls.GenMagLink}.
        /// </summary>
        internal static string GeneratemagnetlinkSettingsCurrentControlsGenMagLink {
            get {
                return ResourceManager.GetString("GeneratemagnetlinkSettingsCurrentControlsGenMagLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        internal static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEADER.
        /// </summary>
        internal static string HEADER {
            get {
                return ResourceManager.GetString("HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide text cursor.
        /// </summary>
        internal static string Hidetextcursor {
            get {
                return ResourceManager.GetString("Hidetextcursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey text color:.
        /// </summary>
        internal static string Hotkeytextcolor {
            get {
                return ResourceManager.GetString("Hotkeytextcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DHT port number..
        /// </summary>
        internal static string InvalidDHTportnumber {
            get {
                return ResourceManager.GetString("InvalidDHTportnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid download speed limit..
        /// </summary>
        internal static string Invaliddownloadspeedlimit {
            get {
                return ResourceManager.GetString("Invaliddownloadspeedlimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File.
        /// </summary>
        internal static string InvalidFile {
            get {
                return ResourceManager.GetString("InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file/folder path..
        /// </summary>
        internal static string Invalidfile_folderpath {
            get {
                return ResourceManager.GetString("Invalidfile/folderpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Folder.
        /// </summary>
        internal static string InvalidFolder {
            get {
                return ResourceManager.GetString("InvalidFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid max connections..
        /// </summary>
        internal static string Invalidmaxconnections {
            get {
                return ResourceManager.GetString("Invalidmaxconnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid max download speed..
        /// </summary>
        internal static string Invalidmaxdownloadspeed {
            get {
                return ResourceManager.GetString("Invalidmaxdownloadspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid maximum connections value..
        /// </summary>
        internal static string Invalidmaximumconnectionsvalue {
            get {
                return ResourceManager.GetString("Invalidmaximumconnectionsvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid max upload speed..
        /// </summary>
        internal static string Invalidmaxuploadspeed {
            get {
                return ResourceManager.GetString("Invalidmaxuploadspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path..
        /// </summary>
        internal static string Invalidpath {
            get {
                return ResourceManager.GetString("Invalidpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid port number..
        /// </summary>
        internal static string Invalidportnumber {
            get {
                return ResourceManager.GetString("Invalidportnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid progress refresh rate..
        /// </summary>
        internal static string Invalidprogressrefreshrate {
            get {
                return ResourceManager.GetString("Invalidprogressrefreshrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tracker URL:.
        /// </summary>
        internal static string InvalidtrackerURL {
            get {
                return ResourceManager.GetString("InvalidtrackerURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid upload speed limit..
        /// </summary>
        internal static string Invaliduploadspeedlimit {
            get {
                return ResourceManager.GetString("Invaliduploadspeedlimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lain Torrent Client.
        /// </summary>
        internal static string LainTorrentClient {
            get {
                return ResourceManager.GetString("LainTorrentClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leechers.
        /// </summary>
        internal static string Leechers {
            get {
                return ResourceManager.GetString("Leechers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Path:.
        /// </summary>
        internal static string LogPath {
            get {
                return ResourceManager.GetString("LogPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log path cannot be empty..
        /// </summary>
        internal static string Logpathcannotbeempty {
            get {
                return ResourceManager.GetString("Logpathcannotbeempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magenta.
        /// </summary>
        internal static string Magenta {
            get {
                return ResourceManager.GetString("Magenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnet link:.
        /// </summary>
        internal static string Magnetlink {
            get {
                return ResourceManager.GetString("Magnetlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnet link copied to clipboard..
        /// </summary>
        internal static string Magnetlinkcopiedtoclipboard {
            get {
                return ResourceManager.GetString("Magnetlinkcopiedtoclipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnet link generated: {magnet.ToV1String()}.
        /// </summary>
        internal static string MagnetlinkgeneratedmagnetToV1String__ {
            get {
                return ResourceManager.GetString("MagnetlinkgeneratedmagnetToV1String()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnet link is empty..
        /// </summary>
        internal static string Magnetlinkisempty {
            get {
                return ResourceManager.GetString("Magnetlinkisempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main.
        /// </summary>
        internal static string main {
            get {
                return ResourceManager.GetString("main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max connections:.
        /// </summary>
        internal static string Maxconnections {
            get {
                return ResourceManager.GetString("Maxconnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max download (MB/s):.
        /// </summary>
        internal static string Maxdownload_MB_s_ {
            get {
                return ResourceManager.GetString("Maxdownload(MB/s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max total connections:.
        /// </summary>
        internal static string Maxtotalconnections {
            get {
                return ResourceManager.GetString("Maxtotalconnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max total download speed (MB/s):.
        /// </summary>
        internal static string Maxtotaldownloadspeed_MB_s_ {
            get {
                return ResourceManager.GetString("Maxtotaldownloadspeed(MB/s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max total upload speed (MB/s):.
        /// </summary>
        internal static string Maxtotaluploadspeed_MB_s_ {
            get {
                return ResourceManager.GetString("Maxtotaluploadspeed(MB/s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max upload (MB/s):.
        /// </summary>
        internal static string Maxupload_MB_s_ {
            get {
                return ResourceManager.GetString("Maxupload(MB/s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Directory.
        /// </summary>
        internal static string MissingDirectory {
            get {
                return ResourceManager.GetString("MissingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active torrents.
        /// </summary>
        internal static string Noactivetorrents {
            get {
                return ResourceManager.GetString("Noactivetorrents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating on port: .
        /// </summary>
        internal static string Operatingonport {
            get {
                return ResourceManager.GetString("Operatingonport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating on port: {Settings.Current.Port}.
        /// </summary>
        internal static string OperatingonportSettingsCurrentPort {
            get {
                return ResourceManager.GetString("OperatingonportSettingsCurrentPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output path:.
        /// </summary>
        internal static string Outputpath {
            get {
                return ResourceManager.GetString("Outputpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output path does not exist..
        /// </summary>
        internal static string Outputpathdoesnotexist {
            get {
                return ResourceManager.GetString("Outputpathdoesnotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused torrent: {manager.Torrent?.Name}.
        /// </summary>
        internal static string PausedtorrentmanagerTorrent_Name {
            get {
                return ResourceManager.GetString("PausedtorrentmanagerTorrent?Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peers.
        /// </summary>
        internal static string Peers {
            get {
                return ResourceManager.GetString("Peers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piece hashed: {e.PieceIndex} - {e.HashPassed}.
        /// </summary>
        internal static string PiecehashedePieceIndex_eHashPassed {
            get {
                return ResourceManager.GetString("PiecehashedePieceIndex-eHashPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piece Size:.
        /// </summary>
        internal static string PieceSize {
            get {
                return ResourceManager.GetString("PieceSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress refresh rate (ms):.
        /// </summary>
        internal static string Progressrefreshrate_ms_ {
            get {
                return ResourceManager.GetString("Progressrefreshrate(ms)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher:.
        /// </summary>
        internal static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumed torrent: {manager.Torrent?.Name}.
        /// </summary>
        internal static string ResumedtorrentmanagerTorrent_Name {
            get {
                return ResourceManager.GetString("ResumedtorrentmanagerTorrent?Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved fast resume data.
        /// </summary>
        internal static string Savedfastresumedata {
            get {
                return ResourceManager.GetString("Savedfastresumedata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeders.
        /// </summary>
        internal static string Seeders {
            get {
                return ResourceManager.GetString("Seeders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a .torrent file.
        /// </summary>
        internal static string Selectatorrentfile {
            get {
                return ResourceManager.GetString("Selectatorrentfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select config file path.
        /// </summary>
        internal static string Selectconfigfilepath {
            get {
                return ResourceManager.GetString("Selectconfigfilepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select default download folder.
        /// </summary>
        internal static string Selectdefaultdownloadfolder {
            get {
                return ResourceManager.GetString("Selectdefaultdownloadfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select download folder.
        /// </summary>
        internal static string Selectdownloadfolder {
            get {
                return ResourceManager.GetString("Selectdownloadfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file does not exist..
        /// </summary>
        internal static string Selectedfiledoesnotexist {
            get {
                return ResourceManager.GetString("Selectedfiledoesnotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected folder does not exist..
        /// </summary>
        internal static string Selectedfolderdoesnotexist {
            get {
                return ResourceManager.GetString("Selectedfolderdoesnotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select filename for the config file..
        /// </summary>
        internal static string Selectfilenamefortheconfigfile {
            get {
                return ResourceManager.GetString("Selectfilenamefortheconfigfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select filename for the log file..
        /// </summary>
        internal static string Selectfilenameforthelogfile {
            get {
                return ResourceManager.GetString("Selectfilenameforthelogfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        internal static string Selectfolder {
            get {
                return ResourceManager.GetString("Selectfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select log file path.
        /// </summary>
        internal static string Selectlogfilepath {
            get {
                return ResourceManager.GetString("Selectlogfilepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select output file.
        /// </summary>
        internal static string Selectoutputfile {
            get {
                return ResourceManager.GetString("Selectoutputfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the default download folder path..
        /// </summary>
        internal static string Selectthedefaultdownloadfolderpath {
            get {
                return ResourceManager.GetString("Selectthedefaultdownloadfolderpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder that contains your files..
        /// </summary>
        internal static string Selectthefolderthatcontainsyourfiles {
            get {
                return ResourceManager.GetString("Selectthefolderthatcontainsyourfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the output .torrent file path..
        /// </summary>
        internal static string Selecttheoutputtorrentfilepath {
            get {
                return ResourceManager.GetString("Selecttheoutputtorrentfilepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select torrent file.
        /// </summary>
        internal static string Selecttorrentfile {
            get {
                return ResourceManager.GetString("Selecttorrentfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Path:.
        /// </summary>
        internal static string SettingsPath {
            get {
                return ResourceManager.GetString("SettingsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings path cannot be empty..
        /// </summary>
        internal static string Settingspathcannotbeempty {
            get {
                return ResourceManager.GetString("Settingspathcannotbeempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start: .
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started seeding: {manager.Torrent?.Name}.
        /// </summary>
        internal static string StartedseedingmanagerTorrent_Name {
            get {
                return ResourceManager.GetString("StartedseedingmanagerTorrent?Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start seeding: .
        /// </summary>
        internal static string Startseeding {
            get {
                return ResourceManager.GetString("Startseeding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start seeding after creation.
        /// </summary>
        internal static string Startseedingaftercreation {
            get {
                return ResourceManager.GetString("Startseedingaftercreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start seeding: {Settings.Current.Controls.StartSeeding}.
        /// </summary>
        internal static string StartseedingSettingsCurrentControlsStartSeeding {
            get {
                return ResourceManager.GetString("StartseedingSettingsCurrentControlsStartSeeding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start: {Settings.Current.Controls.StartDownload}.
        /// </summary>
        internal static string StartSettingsCurrentControlsStartDownload {
            get {
                return ResourceManager.GetString("StartSettingsCurrentControlsStartDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State changed: {e.OldState} -&gt; {e.NewState}.
        /// </summary>
        internal static string StatechangedeOldState__eNewState {
            get {
                return ResourceManager.GetString("StatechangedeOldState->eNewState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop: .
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped seeding: {manager.Torrent?.Name}.
        /// </summary>
        internal static string StoppedseedingmanagerTorrent_Name {
            get {
                return ResourceManager.GetString("StoppedseedingmanagerTorrent?Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop seeding: .
        /// </summary>
        internal static string Stopseeding {
            get {
                return ResourceManager.GetString("Stopseeding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop seeding: {Settings.Current.Controls.StopSeeding}.
        /// </summary>
        internal static string StopseedingSettingsCurrentControlsStopSeeding {
            get {
                return ResourceManager.GetString("StopseedingSettingsCurrentControlsStopSeeding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Seeding When Finished.
        /// </summary>
        internal static string StopSeedingWhenFinished {
            get {
                return ResourceManager.GetString("StopSeedingWhenFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop: {Settings.Current.Controls.StopDownload}.
        /// </summary>
        internal static string StopSettingsCurrentControlsStopDownload {
            get {
                return ResourceManager.GetString("StopSettingsCurrentControlsStopDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color:.
        /// </summary>
        internal static string Textcolor {
            get {
                return ResourceManager.GetString("Textcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This does not appear to be a valid magnet link..
        /// </summary>
        internal static string Thisdoesnotappeartobeavalidmagnetlink {
            get {
                return ResourceManager.GetString("Thisdoesnotappeartobeavalidmagnetlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .torrent.
        /// </summary>
        internal static string torrent {
            get {
                return ResourceManager.GetString("torrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrent created successfully!.
        /// </summary>
        internal static string Torrentcreatedsuccessfully_ {
            get {
                return ResourceManager.GetString("Torrentcreatedsuccessfully!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrent creation failed:.
        /// </summary>
        internal static string Torrentcreationfailed {
            get {
                return ResourceManager.GetString("Torrentcreationfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrent download started..
        /// </summary>
        internal static string Torrentdownloadstarted {
            get {
                return ResourceManager.GetString("Torrentdownloadstarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrent file does not exist..
        /// </summary>
        internal static string Torrentfiledoesnotexist {
            get {
                return ResourceManager.GetString("Torrentfiledoesnotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrent file path:.
        /// </summary>
        internal static string Torrentfilepath {
            get {
                return ResourceManager.GetString("Torrentfilepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrents.
        /// </summary>
        internal static string Torrents {
            get {
                return ResourceManager.GetString("Torrents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to torrents.json.
        /// </summary>
        internal static string torrentsjson {
            get {
                return ResourceManager.GetString("torrentsjson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trackers:.
        /// </summary>
        internal static string Trackers {
            get {
                return ResourceManager.GetString("Trackers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {trimmed}.
        /// </summary>
        internal static string trimmed {
            get {
                return ResourceManager.GetString("trimmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error:.
        /// </summary>
        internal static string Unexpectederror {
            get {
                return ResourceManager.GetString("Unexpectederror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload rate.
        /// </summary>
        internal static string Uploadrate {
            get {
                return ResourceManager.GetString("Uploadrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use magnet link.
        /// </summary>
        internal static string Usemagnetlink {
            get {
                return ResourceManager.GetString("Usemagnetlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select either a magnet link or a torrent file..
        /// </summary>
        internal static string Youmustselecteitheramagnetlinkoratorrentfile {
            get {
                return ResourceManager.GetString("Youmustselecteitheramagnetlinkoratorrentfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd.
        /// </summary>
        internal static string yyyy_MM_dd {
            get {
                return ResourceManager.GetString("yyyy-MM-dd", resourceCulture);
            }
        }
    }
}
