//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace lain {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lain.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _0 {
            get {
                return ResourceManager.GetString("0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   128 KB に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _128KB {
            get {
                return ResourceManager.GetString("128KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   16 KB に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _16KB {
            get {
                return ResourceManager.GetString("16KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 MB に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _1MB {
            get {
                return ResourceManager.GetString("1MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   256 KB に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _256KB {
            get {
                return ResourceManager.GetString("256KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2 MB に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _2MB {
            get {
                return ResourceManager.GetString("2MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   32 KB に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _32KB {
            get {
                return ResourceManager.GetString("32KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   512 KB に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _512KB {
            get {
                return ResourceManager.GetString("512KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   64 KB に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _64KB {
            get {
                return ResourceManager.GetString("64KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ./log.txt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _logtxt {
            get {
                return ResourceManager.GetString("/logtxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Active torrents:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ActiveTorrents {
            get {
                return ResourceManager.GetString("ActiveTorrents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ASCII color: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ASCIIcolor {
            get {
                return ResourceManager.GetString("ASCIIcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background color: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Backgroundcolor {
            get {
                return ResourceManager.GetString("Backgroundcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Black に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BrightBlue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BrightBlue {
            get {
                return ResourceManager.GetString("BrightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BrightCyan に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BrightCyan {
            get {
                return ResourceManager.GetString("BrightCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BrightGreen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BrightGreen {
            get {
                return ResourceManager.GetString("BrightGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BrightMagenta に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BrightMagenta {
            get {
                return ResourceManager.GetString("BrightMagenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BrightRed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BrightRed {
            get {
                return ResourceManager.GetString("BrightRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BrightYellow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BrightYellow {
            get {
                return ResourceManager.GetString("BrightYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///    {c}  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string c {
            get {
                return ResourceManager.GetString("c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   cfg.json に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cfgjson {
            get {
                return ResourceManager.GetString("cfgjson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChooseColor {
            get {
                return ResourceManager.GetString("ChooseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comment: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creating... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Creating {
            get {
                return ResourceManager.GetString("Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cyan に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cyan {
            get {
                return ResourceManager.GetString("Cyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DarkGray に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DarkGray {
            get {
                return ResourceManager.GetString("DarkGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default Download Path: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultDownloadPath {
            get {
                return ResourceManager.GetString("DefaultDownloadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleted files at:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeletedfilesatmanagerSavePath {
            get {
                return ResourceManager.GetString("DeletedfilesatmanagerSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete downloaded files? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Deletedownloadedfiles_ {
            get {
                return ResourceManager.GetString("Deletedownloadedfiles?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleted torrent:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeletedtorrentmanagerTorrent_Name {
            get {
                return ResourceManager.GetString("DeletedtorrentmanagerTorrent?Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeleteSettingsCurrentControlsRemoveTorrent {
            get {
                return ResourceManager.GetString("DeleteSettingsCurrentControlsRemoveTorrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DHT: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DHTEngineDhtState {
            get {
                return ResourceManager.GetString("DHTEngineDhtState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DHT port: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DHTport {
            get {
                return ResourceManager.GetString("DHTport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable ASCII に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisableASCII {
            get {
                return ResourceManager.GetString("DisableASCII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable colored hotkey information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Disablecoloredhotkeyinformation {
            get {
                return ResourceManager.GetString("Disablecoloredhotkeyinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downloading from magnet link... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Downloadingfrommagnetlink {
            get {
                return ResourceManager.GetString("Downloadingfrommagnetlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downloading from torrent file... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Downloadingfromtorrentfile {
            get {
                return ResourceManager.GetString("Downloadingfromtorrentfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download path: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Downloadpath {
            get {
                return ResourceManager.GetString("Downloadpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download path cannot be empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Downloadpathcannotbeempty {
            get {
                return ResourceManager.GetString("Downloadpathcannotbeempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download path does not exist. Create it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DownloadpathdoesnotexistCreateit_ {
            get {
                return ResourceManager.GetString("DownloadpathdoesnotexistCreateit?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download rate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Downloadrate {
            get {
                return ResourceManager.GetString("Downloadrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable detailed logging に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Enabledetailedlogging {
            get {
                return ResourceManager.GetString("Enabledetailedlogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable DHT に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnableDHT {
            get {
                return ResourceManager.GetString("EnableDHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Port Forwarding に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnablePortForwarding {
            get {
                return ResourceManager.GetString("EnablePortForwarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error deleting torrent: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrordeletingtorrentexMessage {
            get {
                return ResourceManager.GetString("ErrordeletingtorrentexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error loading settings: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorloadingsettingsexMessage {
            get {
                return ResourceManager.GetString("ErrorloadingsettingsexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error loading torrents: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Errorloadingtorrents {
            get {
                return ResourceManager.GetString("Errorloadingtorrents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error pausing torrent: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorpausingtorrentexMessage {
            get {
                return ResourceManager.GetString("ErrorpausingtorrentexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error resuming torrent: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorresumingtorrentexMessage {
            get {
                return ResourceManager.GetString("ErrorresumingtorrentexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error saving fastresume data: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Errorsavingfastresumedataex {
            get {
                return ResourceManager.GetString("Errorsavingfastresumedataex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error saving settings: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorsavingsettingsexMessage {
            get {
                return ResourceManager.GetString("ErrorsavingsettingsexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error saving torrents: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorsavingtorrentsexMessage {
            get {
                return ResourceManager.GetString("ErrorsavingtorrentsexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error starting seeding: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorstartingseedingexMessage {
            get {
                return ResourceManager.GetString("ErrorstartingseedingexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error stopping seeding: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorstoppingseedingexMessage {
            get {
                return ResourceManager.GetString("ErrorstoppingseedingexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exit_ {
            get {
                return ResourceManager.GetString("Exit?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fast resume data saved for torrent: {Managers[index].Torrent?.Name} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FastresumedatasavedfortorrentManagers_index_Torrent_Name {
            get {
                return ResourceManager.GetString("FastresumedatasavedfortorrentManagers[index]Torrent?Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fatal Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File/Folder: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_Folder {
            get {
                return ResourceManager.GetString("File/Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Focus background color: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Focusbackgroundcolor {
            get {
                return ResourceManager.GetString("Focusbackgroundcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Focus text color: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Focustextcolor {
            get {
                return ResourceManager.GetString("Focustextcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generate magnet link: {Settings.Current.Controls.GenMagLink} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GeneratemagnetlinkSettingsCurrentControlsGenMagLink {
            get {
                return ResourceManager.GetString("GeneratemagnetlinkSettingsCurrentControlsGenMagLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gray に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Green に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HEADER に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HEADER {
            get {
                return ResourceManager.GetString("HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide text cursor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Hidetextcursor {
            get {
                return ResourceManager.GetString("Hidetextcursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hotkey text color: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Hotkeytextcolor {
            get {
                return ResourceManager.GetString("Hotkeytextcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid DHT port number. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidDHTportnumber {
            get {
                return ResourceManager.GetString("InvalidDHTportnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid download speed limit. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Invaliddownloadspeedlimit {
            get {
                return ResourceManager.GetString("Invaliddownloadspeedlimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidFile {
            get {
                return ResourceManager.GetString("InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid file/folder path. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Invalidfile_folderpath {
            get {
                return ResourceManager.GetString("Invalidfile/folderpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidFolder {
            get {
                return ResourceManager.GetString("InvalidFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid max connections. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Invalidmaxconnections {
            get {
                return ResourceManager.GetString("Invalidmaxconnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid max download speed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Invalidmaxdownloadspeed {
            get {
                return ResourceManager.GetString("Invalidmaxdownloadspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid maximum connections value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Invalidmaximumconnectionsvalue {
            get {
                return ResourceManager.GetString("Invalidmaximumconnectionsvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid max upload speed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Invalidmaxuploadspeed {
            get {
                return ResourceManager.GetString("Invalidmaxuploadspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid path. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Invalidpath {
            get {
                return ResourceManager.GetString("Invalidpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid port number. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Invalidportnumber {
            get {
                return ResourceManager.GetString("Invalidportnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid progress refresh rate. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Invalidprogressrefreshrate {
            get {
                return ResourceManager.GetString("Invalidprogressrefreshrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid tracker URL: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidtrackerURL {
            get {
                return ResourceManager.GetString("InvalidtrackerURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid upload speed limit. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Invaliduploadspeedlimit {
            get {
                return ResourceManager.GetString("Invaliduploadspeedlimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lain Torrent Client に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LainTorrentClient {
            get {
                return ResourceManager.GetString("LainTorrentClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Leechers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Leechers {
            get {
                return ResourceManager.GetString("Leechers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log Path: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogPath {
            get {
                return ResourceManager.GetString("LogPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log path cannot be empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Logpathcannotbeempty {
            get {
                return ResourceManager.GetString("Logpathcannotbeempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Magenta に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Magenta {
            get {
                return ResourceManager.GetString("Magenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Magnet link: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Magnetlink {
            get {
                return ResourceManager.GetString("Magnetlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Magnet link copied to clipboard. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Magnetlinkcopiedtoclipboard {
            get {
                return ResourceManager.GetString("Magnetlinkcopiedtoclipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Magnet link generated:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MagnetlinkgeneratedmagnetToV1String__ {
            get {
                return ResourceManager.GetString("MagnetlinkgeneratedmagnetToV1String()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Magnet link is empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Magnetlinkisempty {
            get {
                return ResourceManager.GetString("Magnetlinkisempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   main に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string main {
            get {
                return ResourceManager.GetString("main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max connections: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Maxconnections {
            get {
                return ResourceManager.GetString("Maxconnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max download (MB/s): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Maxdownload_MB_s_ {
            get {
                return ResourceManager.GetString("Maxdownload(MB/s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max total connections: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Maxtotalconnections {
            get {
                return ResourceManager.GetString("Maxtotalconnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max total download speed (MB/s): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Maxtotaldownloadspeed_MB_s_ {
            get {
                return ResourceManager.GetString("Maxtotaldownloadspeed(MB/s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max total upload speed (MB/s): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Maxtotaluploadspeed_MB_s_ {
            get {
                return ResourceManager.GetString("Maxtotaluploadspeed(MB/s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max upload (MB/s): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Maxupload_MB_s_ {
            get {
                return ResourceManager.GetString("Maxupload(MB/s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Missing Directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MissingDirectory {
            get {
                return ResourceManager.GetString("MissingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No active torrents に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Noactivetorrents {
            get {
                return ResourceManager.GetString("Noactivetorrents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operating on port:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Operatingonport {
            get {
                return ResourceManager.GetString("Operatingonport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output path: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Outputpath {
            get {
                return ResourceManager.GetString("Outputpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output path does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Outputpathdoesnotexist {
            get {
                return ResourceManager.GetString("Outputpathdoesnotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paused torrent: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PausedtorrentmanagerTorrent_Name {
            get {
                return ResourceManager.GetString("PausedtorrentmanagerTorrent?Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Peers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Peers {
            get {
                return ResourceManager.GetString("Peers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Piece hashed: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PiecehashedePieceIndex_eHashPassed {
            get {
                return ResourceManager.GetString("PiecehashedePieceIndex-eHashPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Piece Size: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PieceSize {
            get {
                return ResourceManager.GetString("PieceSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Private に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Progress に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Progress refresh rate (ms): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Progressrefreshrate_ms_ {
            get {
                return ResourceManager.GetString("Progressrefreshrate(ms)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Publisher: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Red に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resumed torrent: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResumedtorrentmanagerTorrent_Name {
            get {
                return ResourceManager.GetString("ResumedtorrentmanagerTorrent?Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saved fast resume data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Savedfastresumedata {
            get {
                return ResourceManager.GetString("Savedfastresumedata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seeders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Seeders {
            get {
                return ResourceManager.GetString("Seeders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a .torrent file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Selectatorrentfile {
            get {
                return ResourceManager.GetString("Selectatorrentfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select config file path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Selectconfigfilepath {
            get {
                return ResourceManager.GetString("Selectconfigfilepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select default download folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Selectdefaultdownloadfolder {
            get {
                return ResourceManager.GetString("Selectdefaultdownloadfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select download folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Selectdownloadfolder {
            get {
                return ResourceManager.GetString("Selectdownloadfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected file does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Selectedfiledoesnotexist {
            get {
                return ResourceManager.GetString("Selectedfiledoesnotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected folder does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Selectedfolderdoesnotexist {
            get {
                return ResourceManager.GetString("Selectedfolderdoesnotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select filename for the config file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Selectfilenamefortheconfigfile {
            get {
                return ResourceManager.GetString("Selectfilenamefortheconfigfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select filename for the log file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Selectfilenameforthelogfile {
            get {
                return ResourceManager.GetString("Selectfilenameforthelogfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Selectfolder {
            get {
                return ResourceManager.GetString("Selectfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select log file path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Selectlogfilepath {
            get {
                return ResourceManager.GetString("Selectlogfilepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select output file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Selectoutputfile {
            get {
                return ResourceManager.GetString("Selectoutputfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the default download folder path. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Selectthedefaultdownloadfolderpath {
            get {
                return ResourceManager.GetString("Selectthedefaultdownloadfolderpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the folder that contains your files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Selectthefolderthatcontainsyourfiles {
            get {
                return ResourceManager.GetString("Selectthefolderthatcontainsyourfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the output .torrent file path. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Selecttheoutputtorrentfilepath {
            get {
                return ResourceManager.GetString("Selecttheoutputtorrentfilepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select torrent file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Selecttorrentfile {
            get {
                return ResourceManager.GetString("Selecttorrentfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings Path: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsPath {
            get {
                return ResourceManager.GetString("SettingsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings path cannot be empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Settingspathcannotbeempty {
            get {
                return ResourceManager.GetString("Settingspathcannotbeempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings saved に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Settingssaved {
            get {
                return ResourceManager.GetString("Settingssaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings saved successfully.
        /// Some changes will take effect after restarting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Settingssavedsuccessfully {
            get {
                return ResourceManager.GetString("Settingssavedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Started seeding: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartedseedingmanagerTorrent_Name {
            get {
                return ResourceManager.GetString("StartedseedingmanagerTorrent?Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start seeding:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Startseeding {
            get {
                return ResourceManager.GetString("Startseeding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start seeding after creation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Startseedingaftercreation {
            get {
                return ResourceManager.GetString("Startseedingaftercreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start seeding: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartseedingSettingsCurrentControlsStartSeeding {
            get {
                return ResourceManager.GetString("StartseedingSettingsCurrentControlsStartSeeding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartSettingsCurrentControlsStartDownload {
            get {
                return ResourceManager.GetString("StartSettingsCurrentControlsStartDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   State に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   State changed: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatechangedeOldState__eNewState {
            get {
                return ResourceManager.GetString("StatechangedeOldState->eNewState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stopped seeding: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StoppedseedingmanagerTorrent_Name {
            get {
                return ResourceManager.GetString("StoppedseedingmanagerTorrent?Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop seeding:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Stopseeding {
            get {
                return ResourceManager.GetString("Stopseeding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop Seeding When Finished に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StopSeedingWhenFinished {
            get {
                return ResourceManager.GetString("StopSeedingWhenFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Success に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text color: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Textcolor {
            get {
                return ResourceManager.GetString("Textcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This does not appear to be a valid magnet link. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Thisdoesnotappeartobeavalidmagnetlink {
            get {
                return ResourceManager.GetString("Thisdoesnotappeartobeavalidmagnetlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .torrent に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string torrent {
            get {
                return ResourceManager.GetString("torrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Torrent created successfully! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Torrentcreatedsuccessfully_ {
            get {
                return ResourceManager.GetString("Torrentcreatedsuccessfully!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Torrent creation failed: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Torrentcreationfailed {
            get {
                return ResourceManager.GetString("Torrentcreationfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Torrent download failed: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Torrentdownloadfailed {
            get {
                return ResourceManager.GetString("Torrentdownloadfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Torrent download started. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Torrentdownloadstarted {
            get {
                return ResourceManager.GetString("Torrentdownloadstarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Torrent file does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Torrentfiledoesnotexist {
            get {
                return ResourceManager.GetString("Torrentfiledoesnotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Torrent file path: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Torrentfilepath {
            get {
                return ResourceManager.GetString("Torrentfilepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Torrents に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Torrents {
            get {
                return ResourceManager.GetString("Torrents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   torrents.json に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string torrentsjson {
            get {
                return ResourceManager.GetString("torrentsjson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trackers: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Trackers {
            get {
                return ResourceManager.GetString("Trackers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {trimmed} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string trimmed {
            get {
                return ResourceManager.GetString("trimmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected error: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Unexpectederror {
            get {
                return ResourceManager.GetString("Unexpectederror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload rate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Uploadrate {
            get {
                return ResourceManager.GetString("Uploadrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use magnet link に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Usemagnetlink {
            get {
                return ResourceManager.GetString("Usemagnetlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   White に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You must select either a magnet link or a torrent file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Youmustselecteitheramagnetlinkoratorrentfile {
            get {
                return ResourceManager.GetString("Youmustselecteitheramagnetlinkoratorrentfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yyyy-MM-dd に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string yyyy_MM_dd {
            get {
                return ResourceManager.GetString("yyyy-MM-dd", resourceCulture);
            }
        }
    }
}
